#\u670D\u52A1\u5668\u7AEF\u53E3\u53F7
server:
  port: 8848

spring:
  #\u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.199.202.220:3306/flower
    username: user14
    password: User123456
    #redis\u7F13\u5B58
  redis:
    host: 127.0.0.1
    port: 6379
    #\u914D\u7F6Ethymeleaf\u9B54\u677F
  thymeleaf:
    #\u5173\u95ED\u9875\u9762\u7F13\u5B58
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  # \u914D\u7F6Efreemarker\u9B54\u677F
  freemarker:
    #\u5173\u95ED\u9875\u9762\u7F13\u5B58
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftlh
    template-loader-path: classpath:/templates/
#\u522B\u540D\u5B9A\u4E49
mybatis:
  type-aliases-package: com.gaoshu.bean
  #\u914D\u7F6E\u5168\u5C40\u914D\u7F6E\u6587\u4EF6
 #config-location: classpath:SqlMapConfig.xml
#\u914D\u7F6E\u6620\u5C04\u6587\u4EF6
    mapper-locations: classpath:mapper/*Mapper.xml

